// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/unit/usecases/calculate_project_progress_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todolist/features/tasks/domain/entities/project.dart' as _i2;
import 'package:todolist/features/tasks/domain/entities/task.dart' as _i5;
import 'package:todolist/features/tasks/domain/repositories/project_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProject_0 extends _i1.SmartFake implements _i2.Project {
  _FakeProject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectStatistics_1 extends _i1.SmartFake
    implements _i3.ProjectStatistics {
  _FakeProjectStatistics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i3.ProjectRepository {
  MockProjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Project?> getProject({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i4.Future<_i2.Project?>.value(),
      ) as _i4.Future<_i2.Project?>);

  @override
  _i4.Future<List<_i2.Project>> getProjects({
    required String? workspaceId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
          {
            #workspaceId: workspaceId,
            #status: status,
          },
        ),
        returnValue: _i4.Future<List<_i2.Project>>.value(<_i2.Project>[]),
      ) as _i4.Future<List<_i2.Project>>);

  @override
  _i4.Future<_i2.Project> createProject({
    required String? workspaceId,
    required _i2.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [],
          {
            #workspaceId: workspaceId,
            #project: project,
          },
        ),
        returnValue: _i4.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #createProject,
            [],
            {
              #workspaceId: workspaceId,
              #project: project,
            },
          ),
        )),
      ) as _i4.Future<_i2.Project>);

  @override
  _i4.Future<_i2.Project> updateProject({
    required String? workspaceId,
    required _i2.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [],
          {
            #workspaceId: workspaceId,
            #project: project,
          },
        ),
        returnValue: _i4.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #updateProject,
            [],
            {
              #workspaceId: workspaceId,
              #project: project,
            },
          ),
        )),
      ) as _i4.Future<_i2.Project>);

  @override
  _i4.Future<void> deleteProject({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TaskEntity>> getProjectTasks({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectTasks,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i4.Future<List<_i5.TaskEntity>>.value(<_i5.TaskEntity>[]),
      ) as _i4.Future<List<_i5.TaskEntity>>);

  @override
  _i4.Future<_i3.ProjectStatistics> getProjectStatistics({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectStatistics,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue:
            _i4.Future<_i3.ProjectStatistics>.value(_FakeProjectStatistics_1(
          this,
          Invocation.method(
            #getProjectStatistics,
            [],
            {
              #workspaceId: workspaceId,
              #projectId: projectId,
            },
          ),
        )),
      ) as _i4.Future<_i3.ProjectStatistics>);

  @override
  _i4.Future<List<_i2.Project>> searchProjects({
    required String? workspaceId,
    required String? query,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProjects,
          [],
          {
            #workspaceId: workspaceId,
            #query: query,
            #status: status,
          },
        ),
        returnValue: _i4.Future<List<_i2.Project>>.value(<_i2.Project>[]),
      ) as _i4.Future<List<_i2.Project>>);
}
