// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8yXfdLv7uuIyHoyERN2yHZhHXqxobLY4',
    appId: '1:909038486197:web:your-web-app-id',
    messagingSenderId: '909038486197',
    projectId: 'todolist-kingnguyen',
    authDomain: 'todolist-kingnguyen.firebaseapp.com',
    databaseURL: 'https://todolist-kingnguyen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todolist-kingnguyen.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8yXfdLv7uuIyHoyERN2yHZhHXqxobLY4',
    appId: '1:909038486197:android:f6dc6b585aa60a8b2f34fc',
    messagingSenderId: '909038486197',
    projectId: 'todolist-kingnguyen',
    databaseURL: 'https://todolist-kingnguyen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todolist-kingnguyen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDupSCnrwK5oW11qQJxhU37r_k3Lg3dGiI',
    appId: '1:909038486197:ios:2eebfc99b7bf72532f34fc',
    messagingSenderId: '909038486197',
    projectId: 'todolist-kingnguyen',
    databaseURL: 'https://todolist-kingnguyen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todolist-kingnguyen.firebasestorage.app',
    iosBundleId: 'com.kingnguyen.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDupSCnrwK5oW11qQJxhU37r_k3Lg3dGiI',
    appId: '1:909038486197:ios:2eebfc99b7bf72532f34fc',
    messagingSenderId: '909038486197',
    projectId: 'todolist-kingnguyen',
    databaseURL: 'https://todolist-kingnguyen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todolist-kingnguyen.firebasestorage.app',
    iosBundleId: 'com.kingnguyen.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8yXfdLv7uuIyHoyERN2yHZhHXqxobLY4',
    appId: '1:909038486197:web:your-windows-app-id',
    messagingSenderId: '909038486197',
    projectId: 'todolist-kingnguyen',
    authDomain: 'todolist-kingnguyen.firebaseapp.com',
    databaseURL: 'https://todolist-kingnguyen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todolist-kingnguyen.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
