// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/unit/controllers/auth_controller_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i17;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i3;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:flutter/material.dart' as _i16;
import 'package:get/get.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:todolist/core/services/firebase_database_service.dart' as _i8;
import 'package:todolist/core/services/navigation_service.dart' as _i15;
import 'package:todolist/core/services/snackbar_service.dart' as _i18;
import 'package:todolist/core/services/storage_service.dart' as _i14;
import 'package:todolist/features/auth/domain/entities/company.dart' as _i13;
import 'package:todolist/features/auth/domain/entities/user.dart' as _i9;
import 'package:todolist/features/reports/domain/entities/report.dart' as _i12;
import 'package:todolist/features/tasks/domain/entities/project.dart' as _i10;
import 'package:todolist/features/tasks/domain/entities/task.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActionCodeInfo_1 extends _i1.SmartFake
    implements _i3.ActionCodeInfo {
  _FakeActionCodeInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_2 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_3 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordValidationStatus_4 extends _i1.SmartFake
    implements _i3.PasswordValidationStatus {
  _FakePasswordValidationStatus_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserMetadata_5 extends _i1.SmartFake implements _i3.UserMetadata {
  _FakeUserMetadata_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactor_6 extends _i1.SmartFake implements _i4.MultiFactor {
  _FakeMultiFactor_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdTokenResult_7 extends _i1.SmartFake implements _i3.IdTokenResult {
  _FakeIdTokenResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_8 extends _i1.SmartFake implements _i4.User {
  _FakeUser_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_9<T> extends _i1.SmartFake
    implements _i5.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i4.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
        Invocation.setter(
          #tenantId,
          tenantId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
        Invocation.setter(
          #customAuthDomain,
          customAuthDomain,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i6.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #useAuthEmulator,
          [
            host,
            port,
          ],
          {#automaticHostMapping: automaticHostMapping},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> applyActionCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #applyActionCode,
          [code],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkActionCode,
          [code],
        ),
        returnValue: _i6.Future<_i3.ActionCodeInfo>.value(_FakeActionCodeInfo_1(
          this,
          Invocation.method(
            #checkActionCode,
            [code],
          ),
        )),
      ) as _i6.Future<_i3.ActionCodeInfo>);

  @override
  _i6.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [],
          {
            #code: code,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> getRedirectResult() => (super.noSuchMethod(
        Invocation.method(
          #getRedirectResult,
          [],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #getRedirectResult,
            [],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) => (super.noSuchMethod(
        Invocation.method(
          #isSignInWithEmailLink,
          [emailLink],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i4.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i6.Stream<_i4.User?>.empty(),
      ) as _i6.Stream<_i4.User?>);

  @override
  _i6.Stream<_i4.User?> idTokenChanges() => (super.noSuchMethod(
        Invocation.method(
          #idTokenChanges,
          [],
        ),
        returnValue: _i6.Stream<_i4.User?>.empty(),
      ) as _i6.Stream<_i4.User?>);

  @override
  _i6.Stream<_i4.User?> userChanges() => (super.noSuchMethod(
        Invocation.method(
          #userChanges,
          [],
        ),
        returnValue: _i6.Stream<_i4.User?>.empty(),
      ) as _i6.Stream<_i4.User?>);

  @override
  _i6.Future<void> sendPasswordResetEmail({
    required String? email,
    _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {
            #email: email,
            #actionCodeSettings: actionCodeSettings,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSignInLinkToEmail,
          [],
          {
            #email: email,
            #actionCodeSettings: actionCodeSettings,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setLanguageCode(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguageCode,
          [languageCode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSettings,
          [],
          {
            #appVerificationDisabledForTesting:
                appVerificationDisabledForTesting,
            #userAccessGroup: userAccessGroup,
            #phoneNumber: phoneNumber,
            #smsCode: smsCode,
            #forceRecaptchaFlow: forceRecaptchaFlow,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setPersistence(_i3.Persistence? persistence) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPersistence,
          [persistence],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserCredential> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> signInWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithCredential,
          [credential],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithCredential,
            [credential],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithCustomToken,
          [token],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithCustomToken,
            [token],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailLink,
          [],
          {
            #email: email,
            #emailLink: emailLink,
          },
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithEmailLink,
            [],
            {
              #email: email,
              #emailLink: emailLink,
            },
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> signInWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithProvider,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithProvider,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i6.Future<_i4.ConfirmationResult>.value(_FakeConfirmationResult_3(
          this,
          Invocation.method(
            #signInWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ConfirmationResult>);

  @override
  _i6.Future<_i4.UserCredential> signInWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPopup,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithPopup,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> signInWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithRedirect,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPasswordResetCode,
          [code],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #verifyPasswordResetCode,
            [code],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i3.PhoneMultiFactorInfo? multiFactorInfo,
    required _i3.PhoneVerificationCompleted? verificationCompleted,
    required _i3.PhoneVerificationFailed? verificationFailed,
    required _i3.PhoneCodeSent? codeSent,
    required _i3.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i3.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneNumber,
          [],
          {
            #phoneNumber: phoneNumber,
            #multiFactorInfo: multiFactorInfo,
            #verificationCompleted: verificationCompleted,
            #verificationFailed: verificationFailed,
            #codeSent: codeSent,
            #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
            #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
            #timeout: timeout,
            #forceResendingToken: forceResendingToken,
            #multiFactorSession: multiFactorSession,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> revokeTokenWithAuthorizationCode(
          String? authorizationCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeTokenWithAuthorizationCode,
          [authorizationCode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> initializeRecaptchaConfig() => (super.noSuchMethod(
        Invocation.method(
          #initializeRecaptchaConfig,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.PasswordValidationStatus> validatePassword(
    _i4.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validatePassword,
          [
            auth,
            password,
          ],
        ),
        returnValue: _i6.Future<_i3.PasswordValidationStatus>.value(
            _FakePasswordValidationStatus_4(
          this,
          Invocation.method(
            #validatePassword,
            [
              auth,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i3.PasswordValidationStatus>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i4.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  _i3.UserMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeUserMetadata_5(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i3.UserMetadata);

  @override
  List<_i3.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i3.UserInfo>[],
      ) as List<_i3.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i4.MultiFactor get multiFactor => (super.noSuchMethod(
        Invocation.getter(#multiFactor),
        returnValue: _FakeMultiFactor_6(
          this,
          Invocation.getter(#multiFactor),
        ),
      ) as _i4.MultiFactor);

  @override
  _i6.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [forceRefresh],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i3.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdTokenResult,
          [forceRefresh],
        ),
        returnValue: _i6.Future<_i3.IdTokenResult>.value(_FakeIdTokenResult_7(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
      ) as _i6.Future<_i3.IdTokenResult>);

  @override
  _i6.Future<_i4.UserCredential> linkWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithCredential,
          [credential],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> linkWithProvider(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithProvider,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithProvider,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithPopup(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithPopup,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> reauthenticateWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithRedirect,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserCredential> linkWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPopup,
          [provider],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> linkWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithRedirect,
          [provider],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i6.Future<_i4.ConfirmationResult>.value(_FakeConfirmationResult_3(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ConfirmationResult>);

  @override
  _i6.Future<_i4.UserCredential> reauthenticateWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [credential],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> sendEmailVerification(
          [_i3.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [actionCodeSettings],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.User> unlink(String? providerId) => (super.noSuchMethod(
        Invocation.method(
          #unlink,
          [providerId],
        ),
        returnValue: _i6.Future<_i4.User>.value(_FakeUser_8(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
      ) as _i6.Future<_i4.User>);

  @override
  _i6.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhoneNumber(
          _i3.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneNumber,
          [phoneCredential],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(
          #updatePhotoURL,
          [photoURL],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBeforeUpdateEmail,
          [
            newEmail,
            actionCodeSettings,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i4.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [FirebaseDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseDatabaseService extends _i1.Mock
    implements _i8.FirebaseDatabaseService {
  MockFirebaseDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_9<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_9<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> onInit() => (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createUser(_i9.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i9.User?> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i6.Future<_i9.User?>.value(),
      ) as _i6.Future<_i9.User?>);

  @override
  _i6.Future<String> createProject({
    required String? companyId,
    required _i10.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [],
          {
            #companyId: companyId,
            #project: project,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createProject,
            [],
            {
              #companyId: companyId,
              #project: project,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i10.Project?> getProject({
    required String? companyId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [],
          {
            #companyId: companyId,
            #projectId: projectId,
          },
        ),
        returnValue: _i6.Future<_i10.Project?>.value(),
      ) as _i6.Future<_i10.Project?>);

  @override
  _i6.Future<List<_i10.Project>> listProjects({
    required String? companyId,
    String? departmentId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listProjects,
          [],
          {
            #companyId: companyId,
            #departmentId: departmentId,
            #status: status,
          },
        ),
        returnValue: _i6.Future<List<_i10.Project>>.value(<_i10.Project>[]),
      ) as _i6.Future<List<_i10.Project>>);

  @override
  _i6.Stream<List<_i10.Project>> watchProjects({
    required String? companyId,
    String? departmentId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchProjects,
          [],
          {
            #companyId: companyId,
            #departmentId: departmentId,
            #status: status,
          },
        ),
        returnValue: _i6.Stream<List<_i10.Project>>.empty(),
      ) as _i6.Stream<List<_i10.Project>>);

  @override
  _i6.Future<void> updateProject({
    required String? companyId,
    required _i10.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [],
          {
            #companyId: companyId,
            #project: project,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> softDeleteProject({
    required String? companyId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteProject,
          [],
          {
            #companyId: companyId,
            #projectId: projectId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> createTask({
    required String? companyId,
    required _i11.TaskEntity? task,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [],
          {
            #companyId: companyId,
            #task: task,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createTask,
            [],
            {
              #companyId: companyId,
              #task: task,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> createReport({
    required String? companyId,
    required _i12.ReportEntity? report,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReport,
          [],
          {
            #companyId: companyId,
            #report: report,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createReport,
            [],
            {
              #companyId: companyId,
              #report: report,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> updateReport({
    required String? companyId,
    required _i12.ReportEntity? report,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReport,
          [],
          {
            #companyId: companyId,
            #report: report,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> submitReport({
    required String? companyId,
    required String? reportId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReport,
          [],
          {
            #companyId: companyId,
            #reportId: reportId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i12.ReportEntity?> getReport({
    required String? companyId,
    required String? reportId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReport,
          [],
          {
            #companyId: companyId,
            #reportId: reportId,
          },
        ),
        returnValue: _i6.Future<_i12.ReportEntity?>.value(),
      ) as _i6.Future<_i12.ReportEntity?>);

  @override
  _i6.Future<List<_i12.ReportEntity>> listReportsByDate({
    required String? companyId,
    required DateTime? date,
    String? userId,
    String? departmentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listReportsByDate,
          [],
          {
            #companyId: companyId,
            #date: date,
            #userId: userId,
            #departmentId: departmentId,
          },
        ),
        returnValue:
            _i6.Future<List<_i12.ReportEntity>>.value(<_i12.ReportEntity>[]),
      ) as _i6.Future<List<_i12.ReportEntity>>);

  @override
  _i6.Stream<List<_i12.ReportEntity>> watchUserReports({
    required String? companyId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserReports,
          [],
          {
            #companyId: companyId,
            #userId: userId,
          },
        ),
        returnValue: _i6.Stream<List<_i12.ReportEntity>>.empty(),
      ) as _i6.Stream<List<_i12.ReportEntity>>);

  @override
  _i6.Future<_i11.TaskEntity?> getTask({
    required String? companyId,
    required String? taskId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [],
          {
            #companyId: companyId,
            #taskId: taskId,
          },
        ),
        returnValue: _i6.Future<_i11.TaskEntity?>.value(),
      ) as _i6.Future<_i11.TaskEntity?>);

  @override
  _i6.Future<void> updateTask({
    required String? companyId,
    required _i11.TaskEntity? task,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [],
          {
            #companyId: companyId,
            #task: task,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> softDeleteTask({
    required String? companyId,
    required String? taskId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteTask,
          [],
          {
            #companyId: companyId,
            #taskId: taskId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.TaskEntity>> listTasks({
    required String? companyId,
    String? type,
    String? status,
    String? priority,
    String? projectId,
    String? assignee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listTasks,
          [],
          {
            #companyId: companyId,
            #type: type,
            #status: status,
            #priority: priority,
            #projectId: projectId,
            #assignee: assignee,
          },
        ),
        returnValue:
            _i6.Future<List<_i11.TaskEntity>>.value(<_i11.TaskEntity>[]),
      ) as _i6.Future<List<_i11.TaskEntity>>);

  @override
  _i6.Stream<List<_i11.TaskEntity>> watchTasks({
    required String? companyId,
    String? type,
    String? status,
    String? priority,
    String? projectId,
    String? assignee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
          {
            #companyId: companyId,
            #type: type,
            #status: status,
            #priority: priority,
            #projectId: projectId,
            #assignee: assignee,
          },
        ),
        returnValue: _i6.Stream<List<_i11.TaskEntity>>.empty(),
      ) as _i6.Stream<List<_i11.TaskEntity>>);

  @override
  _i6.Future<void> updateUser(_i9.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.User>> listUsersByCompany(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listUsersByCompany,
          [companyId],
        ),
        returnValue: _i6.Future<List<_i9.User>>.value(<_i9.User>[]),
      ) as _i6.Future<List<_i9.User>>);

  @override
  _i6.Future<String> createCompany(_i13.Company? company) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCompany,
          [company],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createCompany,
            [company],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<_i13.Company>> listCompaniesCreatedBy(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listCompaniesCreatedBy,
          [userId],
        ),
        returnValue: _i6.Future<List<_i13.Company>>.value(<_i13.Company>[]),
      ) as _i6.Future<List<_i13.Company>>);

  @override
  _i6.Future<_i13.Company?> getCompany(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompany,
          [companyId],
        ),
        returnValue: _i6.Future<_i13.Company?>.value(),
      ) as _i6.Future<_i13.Company?>);

  @override
  _i6.Future<void> updateCompany(_i13.Company? company) => (super.noSuchMethod(
        Invocation.method(
          #updateCompany,
          [company],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> createDepartment({
    required String? companyId,
    required String? name,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDepartment,
          [],
          {
            #companyId: companyId,
            #name: name,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createDepartment,
            [],
            {
              #companyId: companyId,
              #name: name,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> addUserToCompany({
    required String? userId,
    required String? companyId,
    String? departmentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserToCompany,
          [],
          {
            #userId: userId,
            #companyId: companyId,
            #departmentId: departmentId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> companyExists(String? companyId) => (super.noSuchMethod(
        Invocation.method(
          #companyExists,
          [companyId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i13.Company?> getUserCompany(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCompany,
          [userId],
        ),
        returnValue: _i6.Future<_i13.Company?>.value(),
      ) as _i6.Future<_i13.Company?>);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i14.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isStorageAvailable => (super.noSuchMethod(
        Invocation.getter(#isStorageAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  _i6.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  _i6.Future<bool> setBool(
    String? key, {
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [key],
          {#value: value},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  _i6.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  _i6.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i6.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setUserData(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  T? getUserData<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getUserData,
        [key],
      )) as T?);

  @override
  _i6.Future<void> removeUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeUserData,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  T? getSetting<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getSetting,
        [key],
      )) as T?);

  @override
  _i6.Future<void> removeSetting(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeSetting,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setTask(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTask,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  T? getTask<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getTask,
        [key],
      )) as T?);

  @override
  List<T> getAllTasks<T>() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  _i6.Future<void> removeTask(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeTask,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearTasks,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setReport(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReport,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  T? getReport<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getReport,
        [key],
      )) as T?);

  @override
  List<T> getAllReports<T>() => (super.noSuchMethod(
        Invocation.method(
          #getAllReports,
          [],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  _i6.Future<void> removeReport(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeReport,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearReports() => (super.noSuchMethod(
        Invocation.method(
          #clearReports,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setUserToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setCompanyId(String? companyId) => (super.noSuchMethod(
        Invocation.method(
          #setCompanyId,
          [companyId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setDepartmentId(String? departmentId) => (super.noSuchMethod(
        Invocation.method(
          #setDepartmentId,
          [departmentId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #setUserRole,
          [role],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setIsFirstLaunch({required bool? isFirst}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIsFirstLaunch,
          [],
          {#isFirst: isFirst},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getStorageSize() => (super.noSuchMethod(
        Invocation.method(
          #getStorageSize,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i15.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get navigationStack => (super.noSuchMethod(
        Invocation.getter(#navigationStack),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get popupStack => (super.noSuchMethod(
        Invocation.getter(#popupStack),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get alertStack => (super.noSuchMethod(
        Invocation.getter(#alertStack),
        returnValue: <String>[],
      ) as List<String>);

  @override
  int get stackDepth => (super.noSuchMethod(
        Invocation.getter(#stackDepth),
        returnValue: 0,
      ) as int);

  @override
  bool get hasActiveOverlays => (super.noSuchMethod(
        Invocation.getter(#hasActiveOverlays),
        returnValue: false,
      ) as bool);

  @override
  int get activeOverlayCount => (super.noSuchMethod(
        Invocation.getter(#activeOverlayCount),
        returnValue: 0,
      ) as int);

  @override
  _i6.Future<T?> toNamed<T>(
    String? routeName, {
    dynamic arguments,
    Map<String, String>? parameters,
    bool? preventDuplicates = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toNamed,
          [routeName],
          {
            #arguments: arguments,
            #parameters: parameters,
            #preventDuplicates: preventDuplicates,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> offAllNamed<T>(
    String? routeName, {
    dynamic arguments,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #offAllNamed,
          [routeName],
          {
            #arguments: arguments,
            #parameters: parameters,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> offNamed<T>(
    String? routeName, {
    dynamic arguments,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #offNamed,
          [routeName],
          {
            #arguments: arguments,
            #parameters: parameters,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> offNamedUntil<T>(
    String? routeName,
    _i16.RoutePredicate? predicate, {
    dynamic arguments,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #offNamedUntil,
          [
            routeName,
            predicate,
          ],
          {
            #arguments: arguments,
            #parameters: parameters,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void back<T>({
    T? result,
    bool? closeOverlays = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #closeOverlays: closeOverlays,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void backUntil(_i16.RoutePredicate? predicate) => super.noSuchMethod(
        Invocation.method(
          #backUntil,
          [predicate],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void backToRoot() => super.noSuchMethod(
        Invocation.method(
          #backToRoot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<T?> to<T>(
    _i16.Widget? page, {
    _i5.Transition? transition,
    Duration? duration,
    bool? opaque,
    bool? popGesture,
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #to,
          [page],
          {
            #transition: transition,
            #duration: duration,
            #opaque: opaque,
            #popGesture: popGesture,
            #arguments: arguments,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> showDialog<T>({
    required _i16.Widget? child,
    bool? barrierDismissible = true,
    _i17.Color? barrierColor,
    bool? useSafeArea = true,
    Duration? transitionDuration,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #child: child,
            #barrierDismissible: barrierDismissible,
            #barrierColor: barrierColor,
            #useSafeArea: useSafeArea,
            #transitionDuration: transitionDuration,
            #name: name,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> showBottomSheet<T>(
    _i16.Widget? child, {
    _i17.Color? backgroundColor,
    double? elevation,
    _i16.ShapeBorder? shape,
    _i17.Clip? clipBehavior,
    _i17.Color? barrierColor,
    bool? isScrollControlled = false,
    bool? useRootNavigator = false,
    bool? isDismissible = true,
    bool? enableDrag = true,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [child],
          {
            #backgroundColor: backgroundColor,
            #elevation: elevation,
            #shape: shape,
            #clipBehavior: clipBehavior,
            #barrierColor: barrierColor,
            #isScrollControlled: isScrollControlled,
            #useRootNavigator: useRootNavigator,
            #isDismissible: isDismissible,
            #enableDrag: enableDrag,
            #name: name,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void showSnackbar({
    required String? title,
    required String? message,
    _i17.Color? backgroundColor,
    _i17.Color? colorText,
    Duration? duration,
    _i5.SnackPosition? snackPosition,
    _i16.Widget? icon,
    bool? shouldIconPulse,
    double? maxWidth,
    _i16.EdgeInsets? margin,
    _i16.EdgeInsets? padding,
    double? borderRadius,
    _i17.Color? borderColor,
    double? borderWidth,
    _i17.Color? leftBarIndicatorColor,
    List<_i16.BoxShadow>? boxShadows,
    _i16.Gradient? backgroundGradient,
    _i16.TextButton? mainButton,
    _i5.OnTap? onTap,
    bool? isDismissible,
    bool? showProgressIndicator,
    _i16.DismissDirection? dismissDirection,
    _i16.AnimationController? progressIndicatorController,
    _i17.Color? progressIndicatorBackgroundColor,
    _i16.Animation<_i17.Color>? progressIndicatorValueColor,
    _i5.SnackStyle? snackStyle,
    _i16.Curve? forwardAnimationCurve,
    _i16.Curve? reverseAnimationCurve,
    Duration? animationDuration,
    double? overlayBlur,
    _i17.Color? overlayColor,
    String? name,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showSnackbar,
          [],
          {
            #title: title,
            #message: message,
            #backgroundColor: backgroundColor,
            #colorText: colorText,
            #duration: duration,
            #snackPosition: snackPosition,
            #icon: icon,
            #shouldIconPulse: shouldIconPulse,
            #maxWidth: maxWidth,
            #margin: margin,
            #padding: padding,
            #borderRadius: borderRadius,
            #borderColor: borderColor,
            #borderWidth: borderWidth,
            #leftBarIndicatorColor: leftBarIndicatorColor,
            #boxShadows: boxShadows,
            #backgroundGradient: backgroundGradient,
            #mainButton: mainButton,
            #onTap: onTap,
            #isDismissible: isDismissible,
            #showProgressIndicator: showProgressIndicator,
            #dismissDirection: dismissDirection,
            #progressIndicatorController: progressIndicatorController,
            #progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
            #progressIndicatorValueColor: progressIndicatorValueColor,
            #snackStyle: snackStyle,
            #forwardAnimationCurve: forwardAnimationCurve,
            #reverseAnimationCurve: reverseAnimationCurve,
            #animationDuration: animationDuration,
            #overlayBlur: overlayBlur,
            #overlayColor: overlayColor,
            #name: name,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<T?> showAlertDialog<T>({
    required String? title,
    required String? message,
    String? confirmText,
    String? cancelText,
    _i17.VoidCallback? onConfirm,
    _i17.VoidCallback? onCancel,
    bool? barrierDismissible = true,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlertDialog,
          [],
          {
            #title: title,
            #message: message,
            #confirmText: confirmText,
            #cancelText: cancelText,
            #onConfirm: onConfirm,
            #onCancel: onCancel,
            #barrierDismissible: barrierDismissible,
            #name: name,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void closeAllOverlays() => super.noSuchMethod(
        Invocation.method(
          #closeAllOverlays,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getNavigationHistory() => (super.noSuchMethod(
        Invocation.method(
          #getNavigationHistory,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getNavigationHistory,
            [],
          ),
        ),
      ) as String);

  @override
  void printNavigationState() => super.noSuchMethod(
        Invocation.method(
          #printNavigationState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearNavigationTracking() => super.noSuchMethod(
        Invocation.method(
          #clearNavigationTracking,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isRouteInStack(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #isRouteInStack,
          [routeName],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getRoutePosition(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #getRoutePosition,
          [routeName],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [SnackbarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnackbarService extends _i1.Mock implements _i18.SnackbarService {
  MockSnackbarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showSuccess({
    required String? title,
    required String? message,
    Duration? duration = const Duration(seconds: 3),
    _i5.SnackPosition? position = _i5.SnackPosition.TOP,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showSuccess,
          [],
          {
            #title: title,
            #message: message,
            #duration: duration,
            #position: position,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showError({
    required String? title,
    required String? message,
    Duration? duration = const Duration(seconds: 4),
    _i5.SnackPosition? position = _i5.SnackPosition.TOP,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showError,
          [],
          {
            #title: title,
            #message: message,
            #duration: duration,
            #position: position,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showWarning({
    required String? title,
    required String? message,
    Duration? duration = const Duration(seconds: 3),
    _i5.SnackPosition? position = _i5.SnackPosition.TOP,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showWarning,
          [],
          {
            #title: title,
            #message: message,
            #duration: duration,
            #position: position,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showInfo({
    required String? title,
    required String? message,
    Duration? duration = const Duration(seconds: 3),
    _i5.SnackPosition? position = _i5.SnackPosition.TOP,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showInfo,
          [],
          {
            #title: title,
            #message: message,
            #duration: duration,
            #position: position,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showCustom({
    required String? title,
    required String? message,
    _i17.Color? backgroundColor,
    _i17.Color? textColor,
    _i16.IconData? icon,
    Duration? duration = const Duration(seconds: 3),
    _i5.SnackPosition? position = _i5.SnackPosition.TOP,
    _i16.EdgeInsets? margin,
    double? borderRadius,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showCustom,
          [],
          {
            #title: title,
            #message: message,
            #backgroundColor: backgroundColor,
            #textColor: textColor,
            #icon: icon,
            #duration: duration,
            #position: position,
            #margin: margin,
            #borderRadius: borderRadius,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showLoading({
    required String? title,
    required String? message,
    Duration? duration = const Duration(seconds: 2),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showLoading,
          [],
          {
            #title: title,
            #message: message,
            #duration: duration,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskCreated() => super.noSuchMethod(
        Invocation.method(
          #showTaskCreated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskUpdated() => super.noSuchMethod(
        Invocation.method(
          #showTaskUpdated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskDeleted() => super.noSuchMethod(
        Invocation.method(
          #showTaskDeleted,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showTaskCompleted() => super.noSuchMethod(
        Invocation.method(
          #showTaskCompleted,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showNetworkError() => super.noSuchMethod(
        Invocation.method(
          #showNetworkError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showServerError() => super.noSuchMethod(
        Invocation.method(
          #showServerError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showValidationError(String? field) => super.noSuchMethod(
        Invocation.method(
          #showValidationError,
          [field],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showLoginSuccess() => super.noSuchMethod(
        Invocation.method(
          #showLoginSuccess,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showLoginError() => super.noSuchMethod(
        Invocation.method(
          #showLoginError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showRegistrationSuccess() => super.noSuchMethod(
        Invocation.method(
          #showRegistrationSuccess,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showRegistrationError() => super.noSuchMethod(
        Invocation.method(
          #showRegistrationError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showLogoutSuccess() => super.noSuchMethod(
        Invocation.method(
          #showLogoutSuccess,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showCompanySetupSuccess() => super.noSuchMethod(
        Invocation.method(
          #showCompanySetupSuccess,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showCompanySetupError() => super.noSuchMethod(
        Invocation.method(
          #showCompanySetupError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void closeAll() => super.noSuchMethod(
        Invocation.method(
          #closeAll,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
