// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/unit/controllers/paginated_task_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:todolist/core/services/firebase_database_service.dart' as _i5;
import 'package:todolist/core/services/pagination_service.dart' as _i3;
import 'package:todolist/core/services/storage_service.dart' as _i12;
import 'package:todolist/features/auth/domain/entities/company.dart' as _i11;
import 'package:todolist/features/auth/domain/entities/user.dart' as _i6;
import 'package:todolist/features/reports/domain/entities/report.dart' as _i10;
import 'package:todolist/features/tasks/domain/entities/project.dart' as _i7;
import 'package:todolist/features/tasks/domain/entities/task.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResult_1<T1> extends _i1.SmartFake
    implements _i3.PaginatedResult<T1> {
  _FakePaginatedResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaginationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaginationService extends _i1.Mock implements _i3.PaginationService {
  MockPaginationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> onInit() => (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.PaginatedResult<T>> getPaginatedResultsWithCursor<T>({
    required String? cacheKey,
    required _i4.Future<_i3.PaginatedResult<T>> Function(
      String?,
      int,
    )? fetchFunction,
    String? cursor,
    int? pageSize,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginatedResultsWithCursor,
          [],
          {
            #cacheKey: cacheKey,
            #fetchFunction: fetchFunction,
            #cursor: cursor,
            #pageSize: pageSize,
            #useCache: useCache,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginatedResult<T>>.value(_FakePaginatedResult_1<T>(
          this,
          Invocation.method(
            #getPaginatedResultsWithCursor,
            [],
            {
              #cacheKey: cacheKey,
              #fetchFunction: fetchFunction,
              #cursor: cursor,
              #pageSize: pageSize,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginatedResult<T>>);

  @override
  _i4.Future<_i3.PaginatedResult<T>> getPaginatedResults<T>({
    required String? cacheKey,
    required _i4.Future<List<T>> Function(
      int,
      int,
    )? fetchFunction,
    int? page = 1,
    int? pageSize,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginatedResults,
          [],
          {
            #cacheKey: cacheKey,
            #fetchFunction: fetchFunction,
            #page: page,
            #pageSize: pageSize,
            #useCache: useCache,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginatedResult<T>>.value(_FakePaginatedResult_1<T>(
          this,
          Invocation.method(
            #getPaginatedResults,
            [],
            {
              #cacheKey: cacheKey,
              #fetchFunction: fetchFunction,
              #page: page,
              #pageSize: pageSize,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginatedResult<T>>);

  @override
  _i4.Future<_i3.PaginatedResult<T>> getNextPage<T>({
    required String? cacheKey,
    required _i4.Future<List<T>> Function(
      int,
      int,
    )? fetchFunction,
    required _i3.PaginatedResult<T>? currentResult,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextPage,
          [],
          {
            #cacheKey: cacheKey,
            #fetchFunction: fetchFunction,
            #currentResult: currentResult,
            #useCache: useCache,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginatedResult<T>>.value(_FakePaginatedResult_1<T>(
          this,
          Invocation.method(
            #getNextPage,
            [],
            {
              #cacheKey: cacheKey,
              #fetchFunction: fetchFunction,
              #currentResult: currentResult,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginatedResult<T>>);

  @override
  _i4.Future<_i3.PaginatedResult<T>> getPreviousPage<T>({
    required String? cacheKey,
    required _i4.Future<List<T>> Function(
      int,
      int,
    )? fetchFunction,
    required _i3.PaginatedResult<T>? currentResult,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreviousPage,
          [],
          {
            #cacheKey: cacheKey,
            #fetchFunction: fetchFunction,
            #currentResult: currentResult,
            #useCache: useCache,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginatedResult<T>>.value(_FakePaginatedResult_1<T>(
          this,
          Invocation.method(
            #getPreviousPage,
            [],
            {
              #cacheKey: cacheKey,
              #fetchFunction: fetchFunction,
              #currentResult: currentResult,
              #useCache: useCache,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginatedResult<T>>);

  @override
  _i4.Future<_i3.PaginatedResult<T>> refreshPage<T>({
    required String? cacheKey,
    required _i4.Future<List<T>> Function(
      int,
      int,
    )? fetchFunction,
    required _i3.PaginatedResult<T>? currentResult,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshPage,
          [],
          {
            #cacheKey: cacheKey,
            #fetchFunction: fetchFunction,
            #currentResult: currentResult,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginatedResult<T>>.value(_FakePaginatedResult_1<T>(
          this,
          Invocation.method(
            #refreshPage,
            [],
            {
              #cacheKey: cacheKey,
              #fetchFunction: fetchFunction,
              #currentResult: currentResult,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginatedResult<T>>);

  @override
  void clearCache(String? cacheKey) => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [cacheKey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getUserPreferredPageSize() => (super.noSuchMethod(
        Invocation.method(
          #getUserPreferredPageSize,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> setUserPreferredPageSize(int? pageSize) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserPreferredPageSize,
          [pageSize],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FirebaseDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseDatabaseService extends _i1.Mock
    implements _i5.FirebaseDatabaseService {
  MockFirebaseDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> onInit() => (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createUser(_i6.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.User?> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i4.Future<_i6.User?>.value(),
      ) as _i4.Future<_i6.User?>);

  @override
  _i4.Future<String> createProject({
    required String? companyId,
    required _i7.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [],
          {
            #companyId: companyId,
            #project: project,
          },
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createProject,
            [],
            {
              #companyId: companyId,
              #project: project,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i7.Project?> getProject({
    required String? companyId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [],
          {
            #companyId: companyId,
            #projectId: projectId,
          },
        ),
        returnValue: _i4.Future<_i7.Project?>.value(),
      ) as _i4.Future<_i7.Project?>);

  @override
  _i4.Future<List<_i7.Project>> listProjects({
    required String? companyId,
    String? departmentId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listProjects,
          [],
          {
            #companyId: companyId,
            #departmentId: departmentId,
            #status: status,
          },
        ),
        returnValue: _i4.Future<List<_i7.Project>>.value(<_i7.Project>[]),
      ) as _i4.Future<List<_i7.Project>>);

  @override
  _i4.Stream<List<_i7.Project>> watchProjects({
    required String? companyId,
    String? departmentId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchProjects,
          [],
          {
            #companyId: companyId,
            #departmentId: departmentId,
            #status: status,
          },
        ),
        returnValue: _i4.Stream<List<_i7.Project>>.empty(),
      ) as _i4.Stream<List<_i7.Project>>);

  @override
  _i4.Future<void> updateProject({
    required String? companyId,
    required _i7.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [],
          {
            #companyId: companyId,
            #project: project,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteProject({
    required String? companyId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteProject,
          [],
          {
            #companyId: companyId,
            #projectId: projectId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> createTask({
    required String? companyId,
    required _i9.TaskEntity? task,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [],
          {
            #companyId: companyId,
            #task: task,
          },
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createTask,
            [],
            {
              #companyId: companyId,
              #task: task,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> createReport({
    required String? companyId,
    required _i10.ReportEntity? report,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReport,
          [],
          {
            #companyId: companyId,
            #report: report,
          },
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createReport,
            [],
            {
              #companyId: companyId,
              #report: report,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateReport({
    required String? companyId,
    required _i10.ReportEntity? report,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReport,
          [],
          {
            #companyId: companyId,
            #report: report,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> submitReport({
    required String? companyId,
    required String? reportId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReport,
          [],
          {
            #companyId: companyId,
            #reportId: reportId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i10.ReportEntity?> getReport({
    required String? companyId,
    required String? reportId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReport,
          [],
          {
            #companyId: companyId,
            #reportId: reportId,
          },
        ),
        returnValue: _i4.Future<_i10.ReportEntity?>.value(),
      ) as _i4.Future<_i10.ReportEntity?>);

  @override
  _i4.Future<List<_i10.ReportEntity>> listReportsByDate({
    required String? companyId,
    required DateTime? date,
    String? userId,
    String? departmentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listReportsByDate,
          [],
          {
            #companyId: companyId,
            #date: date,
            #userId: userId,
            #departmentId: departmentId,
          },
        ),
        returnValue:
            _i4.Future<List<_i10.ReportEntity>>.value(<_i10.ReportEntity>[]),
      ) as _i4.Future<List<_i10.ReportEntity>>);

  @override
  _i4.Stream<List<_i10.ReportEntity>> watchUserReports({
    required String? companyId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserReports,
          [],
          {
            #companyId: companyId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Stream<List<_i10.ReportEntity>>.empty(),
      ) as _i4.Stream<List<_i10.ReportEntity>>);

  @override
  _i4.Future<_i9.TaskEntity?> getTask({
    required String? companyId,
    required String? taskId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [],
          {
            #companyId: companyId,
            #taskId: taskId,
          },
        ),
        returnValue: _i4.Future<_i9.TaskEntity?>.value(),
      ) as _i4.Future<_i9.TaskEntity?>);

  @override
  _i4.Future<void> updateTask({
    required String? companyId,
    required _i9.TaskEntity? task,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [],
          {
            #companyId: companyId,
            #task: task,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteTask({
    required String? companyId,
    required String? taskId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteTask,
          [],
          {
            #companyId: companyId,
            #taskId: taskId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.TaskEntity>> listTasks({
    required String? companyId,
    String? type,
    String? status,
    String? priority,
    String? projectId,
    String? assignee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listTasks,
          [],
          {
            #companyId: companyId,
            #type: type,
            #status: status,
            #priority: priority,
            #projectId: projectId,
            #assignee: assignee,
          },
        ),
        returnValue: _i4.Future<List<_i9.TaskEntity>>.value(<_i9.TaskEntity>[]),
      ) as _i4.Future<List<_i9.TaskEntity>>);

  @override
  _i4.Stream<List<_i9.TaskEntity>> watchTasks({
    required String? companyId,
    String? type,
    String? status,
    String? priority,
    String? projectId,
    String? assignee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTasks,
          [],
          {
            #companyId: companyId,
            #type: type,
            #status: status,
            #priority: priority,
            #projectId: projectId,
            #assignee: assignee,
          },
        ),
        returnValue: _i4.Stream<List<_i9.TaskEntity>>.empty(),
      ) as _i4.Stream<List<_i9.TaskEntity>>);

  @override
  _i4.Future<void> updateUser(_i6.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.User>> listUsersByCompany(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listUsersByCompany,
          [companyId],
        ),
        returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
      ) as _i4.Future<List<_i6.User>>);

  @override
  _i4.Future<String> createCompany(_i11.Company? company) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCompany,
          [company],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createCompany,
            [company],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<_i11.Company>> listCompaniesCreatedBy(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listCompaniesCreatedBy,
          [userId],
        ),
        returnValue: _i4.Future<List<_i11.Company>>.value(<_i11.Company>[]),
      ) as _i4.Future<List<_i11.Company>>);

  @override
  _i4.Future<_i11.Company?> getCompany(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompany,
          [companyId],
        ),
        returnValue: _i4.Future<_i11.Company?>.value(),
      ) as _i4.Future<_i11.Company?>);

  @override
  _i4.Future<void> updateCompany(_i11.Company? company) => (super.noSuchMethod(
        Invocation.method(
          #updateCompany,
          [company],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> createDepartment({
    required String? companyId,
    required String? name,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDepartment,
          [],
          {
            #companyId: companyId,
            #name: name,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createDepartment,
            [],
            {
              #companyId: companyId,
              #name: name,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> addUserToCompany({
    required String? userId,
    required String? companyId,
    String? departmentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserToCompany,
          [],
          {
            #userId: userId,
            #companyId: companyId,
            #departmentId: departmentId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> companyExists(String? companyId) => (super.noSuchMethod(
        Invocation.method(
          #companyExists,
          [companyId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i11.Company?> getUserCompany(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCompany,
          [userId],
        ),
        returnValue: _i4.Future<_i11.Company?>.value(),
      ) as _i4.Future<_i11.Company?>);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i12.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isStorageAvailable => (super.noSuchMethod(
        Invocation.getter(#isStorageAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  _i4.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  _i4.Future<bool> setBool(
    String? key, {
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [key],
          {#value: value},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  _i4.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  _i4.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i4.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setUserData(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? getUserData<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getUserData,
        [key],
      )) as T?);

  @override
  _i4.Future<void> removeUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeUserData,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? getSetting<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getSetting,
        [key],
      )) as T?);

  @override
  _i4.Future<void> removeSetting(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeSetting,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearSettings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setTask(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTask,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? getTask<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getTask,
        [key],
      )) as T?);

  @override
  List<T> getAllTasks<T>() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  _i4.Future<void> removeTask(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeTask,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearTasks,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setReport(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReport,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  T? getReport<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #getReport,
        [key],
      )) as T?);

  @override
  List<T> getAllReports<T>() => (super.noSuchMethod(
        Invocation.method(
          #getAllReports,
          [],
        ),
        returnValue: <T>[],
      ) as List<T>);

  @override
  _i4.Future<void> removeReport(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeReport,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearReports() => (super.noSuchMethod(
        Invocation.method(
          #clearReports,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setUserToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCompanyId(String? companyId) => (super.noSuchMethod(
        Invocation.method(
          #setCompanyId,
          [companyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setDepartmentId(String? departmentId) => (super.noSuchMethod(
        Invocation.method(
          #setDepartmentId,
          [departmentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #setUserRole,
          [role],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setIsFirstLaunch({required bool? isFirst}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setIsFirstLaunch,
          [],
          {#isFirst: isFirst},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getStorageSize() => (super.noSuchMethod(
        Invocation.method(
          #getStorageSize,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
