// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/unit/controllers/project_controller_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i14;

import 'package:flutter/material.dart' as _i13;
import 'package:get/get.dart' as _i5;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:todolist/core/errors/failures.dart' as _i12;
import 'package:todolist/core/services/workspace_context_service.dart' as _i8;
import 'package:todolist/features/auth/domain/entities/user.dart' as _i10;
import 'package:todolist/features/auth/presentation/controllers/auth_controller.dart'
    as _i11;
import 'package:todolist/features/tasks/domain/entities/project.dart' as _i2;
import 'package:todolist/features/tasks/domain/entities/task.dart' as _i7;
import 'package:todolist/features/tasks/domain/repositories/project_repository.dart'
    as _i3;
import 'package:todolist/features/tasks/domain/usecases/calculate_project_progress.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProject_0 extends _i1.SmartFake implements _i2.Project {
  _FakeProject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectStatistics_1 extends _i1.SmartFake
    implements _i3.ProjectStatistics {
  _FakeProjectStatistics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectProgressResult_2 extends _i1.SmartFake
    implements _i4.ProjectProgressResult {
  _FakeProjectProgressResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectProgressSummary_3 extends _i1.SmartFake
    implements _i4.ProjectProgressSummary {
  _FakeProjectProgressSummary_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_4<T> extends _i1.SmartFake
    implements _i5.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRx_5<T> extends _i1.SmartFake implements _i5.Rx<T> {
  _FakeRx_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i3.ProjectRepository {
  MockProjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Project?> getProject({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i6.Future<_i2.Project?>.value(),
      ) as _i6.Future<_i2.Project?>);

  @override
  _i6.Future<List<_i2.Project>> getProjects({
    required String? workspaceId,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
          {
            #workspaceId: workspaceId,
            #status: status,
          },
        ),
        returnValue: _i6.Future<List<_i2.Project>>.value(<_i2.Project>[]),
      ) as _i6.Future<List<_i2.Project>>);

  @override
  _i6.Future<_i2.Project> createProject({
    required String? workspaceId,
    required _i2.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [],
          {
            #workspaceId: workspaceId,
            #project: project,
          },
        ),
        returnValue: _i6.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #createProject,
            [],
            {
              #workspaceId: workspaceId,
              #project: project,
            },
          ),
        )),
      ) as _i6.Future<_i2.Project>);

  @override
  _i6.Future<_i2.Project> updateProject({
    required String? workspaceId,
    required _i2.Project? project,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [],
          {
            #workspaceId: workspaceId,
            #project: project,
          },
        ),
        returnValue: _i6.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #updateProject,
            [],
            {
              #workspaceId: workspaceId,
              #project: project,
            },
          ),
        )),
      ) as _i6.Future<_i2.Project>);

  @override
  _i6.Future<void> deleteProject({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.TaskEntity>> getProjectTasks({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectTasks,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i6.Future<List<_i7.TaskEntity>>.value(<_i7.TaskEntity>[]),
      ) as _i6.Future<List<_i7.TaskEntity>>);

  @override
  _i6.Future<_i3.ProjectStatistics> getProjectStatistics({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectStatistics,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue:
            _i6.Future<_i3.ProjectStatistics>.value(_FakeProjectStatistics_1(
          this,
          Invocation.method(
            #getProjectStatistics,
            [],
            {
              #workspaceId: workspaceId,
              #projectId: projectId,
            },
          ),
        )),
      ) as _i6.Future<_i3.ProjectStatistics>);

  @override
  _i6.Future<List<_i2.Project>> searchProjects({
    required String? workspaceId,
    required String? query,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProjects,
          [],
          {
            #workspaceId: workspaceId,
            #query: query,
            #status: status,
          },
        ),
        returnValue: _i6.Future<List<_i2.Project>>.value(<_i2.Project>[]),
      ) as _i6.Future<List<_i2.Project>>);
}

/// A class which mocks [CalculateProjectProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateProjectProgress extends _i1.Mock
    implements _i4.CalculateProjectProgress {
  MockCalculateProjectProgress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ProjectProgressResult> call({
    required String? workspaceId,
    required String? projectId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #workspaceId: workspaceId,
            #projectId: projectId,
          },
        ),
        returnValue: _i6.Future<_i4.ProjectProgressResult>.value(
            _FakeProjectProgressResult_2(
          this,
          Invocation.method(
            #call,
            [],
            {
              #workspaceId: workspaceId,
              #projectId: projectId,
            },
          ),
        )),
      ) as _i6.Future<_i4.ProjectProgressResult>);

  @override
  _i6.Future<List<_i4.ProjectProgressResult>> callForMultiple({
    required String? workspaceId,
    required List<String>? projectIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callForMultiple,
          [],
          {
            #workspaceId: workspaceId,
            #projectIds: projectIds,
          },
        ),
        returnValue: _i6.Future<List<_i4.ProjectProgressResult>>.value(
            <_i4.ProjectProgressResult>[]),
      ) as _i6.Future<List<_i4.ProjectProgressResult>>);

  @override
  _i6.Future<_i4.ProjectProgressSummary> getProgressSummary(
          {required String? workspaceId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgressSummary,
          [],
          {#workspaceId: workspaceId},
        ),
        returnValue: _i6.Future<_i4.ProjectProgressSummary>.value(
            _FakeProjectProgressSummary_3(
          this,
          Invocation.method(
            #getProgressSummary,
            [],
            {#workspaceId: workspaceId},
          ),
        )),
      ) as _i6.Future<_i4.ProjectProgressSummary>);
}

/// A class which mocks [WorkspaceContextService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceContextService extends _i1.Mock
    implements _i8.WorkspaceContextService {
  MockWorkspaceContextService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentWorkspaceId => (super.noSuchMethod(
        Invocation.getter(#currentWorkspaceId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#currentWorkspaceId),
        ),
      ) as String);

  @override
  List<_i10.User> get workspaceMembers => (super.noSuchMethod(
        Invocation.getter(#workspaceMembers),
        returnValue: <_i10.User>[],
      ) as List<_i10.User>);

  @override
  List<_i2.Project> get workspaceProjects => (super.noSuchMethod(
        Invocation.getter(#workspaceProjects),
        returnValue: <_i2.Project>[],
      ) as List<_i2.Project>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as String);

  @override
  bool get hasValidWorkspace => (super.noSuchMethod(
        Invocation.getter(#hasValidWorkspace),
        returnValue: false,
      ) as bool);

  @override
  _i5.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> setCurrentWorkspace(String? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentWorkspace,
          [workspaceId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isWorkspaceMember(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isWorkspaceMember,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.User? getWorkspaceMember(String? userId) =>
      (super.noSuchMethod(Invocation.method(
        #getWorkspaceMember,
        [userId],
      )) as _i10.User?);

  @override
  bool isWorkspaceProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #isWorkspaceProject,
          [projectId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.Project? getWorkspaceProject(String? projectId) =>
      (super.noSuchMethod(Invocation.method(
        #getWorkspaceProject,
        [projectId],
      )) as _i2.Project?);

  @override
  _i6.Future<void> refreshWorkspaceData() => (super.noSuchMethod(
        Invocation.method(
          #refreshWorkspaceData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearWorkspaceContext() => super.noSuchMethod(
        Invocation.method(
          #clearWorkspaceContext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getWorkspaceContextInfo() => (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceContextInfo,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i11.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Rx<_i10.User?> get currentUserObservable => (super.noSuchMethod(
        Invocation.getter(#currentUserObservable),
        returnValue: _FakeRx_5<_i10.User?>(
          this,
          Invocation.getter(#currentUserObservable),
        ),
      ) as _i5.Rx<_i10.User?>);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
      ) as bool);

  @override
  bool get isDepartmentManager => (super.noSuchMethod(
        Invocation.getter(#isDepartmentManager),
        returnValue: false,
      ) as bool);

  @override
  bool get isTeamLead => (super.noSuchMethod(
        Invocation.getter(#isTeamLead),
        returnValue: false,
      ) as bool);

  @override
  bool get isRegularUser => (super.noSuchMethod(
        Invocation.getter(#isRegularUser),
        returnValue: false,
      ) as bool);

  @override
  bool get isCompanyAdmin => (super.noSuchMethod(
        Invocation.getter(#isCompanyAdmin),
        returnValue: false,
      ) as bool);

  @override
  bool get isDepartmentAdmin => (super.noSuchMethod(
        Invocation.getter(#isDepartmentAdmin),
        returnValue: false,
      ) as bool);

  @override
  String get userDisplayName => (super.noSuchMethod(
        Invocation.getter(#userDisplayName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#userDisplayName),
        ),
      ) as String);

  @override
  String get userInitials => (super.noSuchMethod(
        Invocation.getter(#userInitials),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#userInitials),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isSuccess => (super.noSuchMethod(
        Invocation.getter(#isSuccess),
        returnValue: false,
      ) as bool);

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isSuccess(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isSuccess,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_4<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void setAuthenticatedUserForTest(
    String? id,
    String? email,
    String? name,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAuthenticatedUserForTest,
          [
            id,
            email,
            name,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> handlePostLoginNavigation() => (super.noSuchMethod(
        Invocation.method(
          #handlePostLoginNavigation,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> changePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [newPassword],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserProfile({
    String? name,
    String? profileImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #name: name,
            #profileImageUrl: profileImageUrl,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool hasPermission(String? permission) => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [permission],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canManageRole(String? targetRole) => (super.noSuchMethod(
        Invocation.method(
          #canManageRole,
          [targetRole],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasHigherAuthorityThan(String? targetRole) => (super.noSuchMethod(
        Invocation.method(
          #hasHigherAuthorityThan,
          [targetRole],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String> getCurrentUserPermissions() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserPermissions,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void setError(_i12.Failure? failure) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [failure],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearStates() => super.noSuchMethod(
        Invocation.method(
          #clearStates,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleError(_i12.Failure? failure) => super.noSuchMethod(
        Invocation.method(
          #handleError,
          [failure],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleSuccess([String? message]) => super.noSuchMethod(
        Invocation.method(
          #handleSuccess,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<T?> executeAsync<T>(
    _i6.Future<T> Function()? operation, {
    bool? showLoading = true,
    String? successMessage,
    bool? showError = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeAsync,
          [operation],
          {
            #showLoading: showLoading,
            #successMessage: successMessage,
            #showError: showError,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> navigateTo<T>(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> navigateOffAll<T>(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateOffAll,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> navigateOff<T>(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateOff,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void navigateBack<T>({T? result}) => super.noSuchMethod(
        Invocation.method(
          #navigateBack,
          [],
          {#result: result},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateBackToRoot() => super.noSuchMethod(
        Invocation.method(
          #navigateBackToRoot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<T?> showDialog<T>(
    _i13.Widget? child, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [child],
          {#name: name},
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> showBottomSheet<T>(
    _i13.Widget? child, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [child],
          {#name: name},
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<T?> showAlertDialog<T>({
    required String? title,
    required String? message,
    String? confirmText,
    String? cancelText,
    _i14.VoidCallback? onConfirm,
    _i14.VoidCallback? onCancel,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlertDialog,
          [],
          {
            #title: title,
            #message: message,
            #confirmText: confirmText,
            #cancelText: cancelText,
            #onConfirm: onConfirm,
            #onCancel: onCancel,
            #name: name,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  void printNavigationState() => super.noSuchMethod(
        Invocation.method(
          #printNavigationState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Disposer addListener(_i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i15.Disposer);

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i14.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Disposer addListenerId(
    Object? key,
    _i15.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i15.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
