// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/integration/invitation_flow_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i3;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:get/get.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:todolist/core/constants/task_enums.dart' as _i11;
import 'package:todolist/core/services/firebase_database_service_enhanced.dart'
    as _i7;
import 'package:todolist/core/services/pagination_service.dart' as _i6;
import 'package:todolist/features/auth/domain/entities/user.dart' as _i14;
import 'package:todolist/features/reports/domain/entities/report.dart' as _i13;
import 'package:todolist/features/tasks/domain/entities/project.dart' as _i12;
import 'package:todolist/features/tasks/domain/entities/task.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActionCodeInfo_1 extends _i1.SmartFake
    implements _i3.ActionCodeInfo {
  _FakeActionCodeInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_2 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_3 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordValidationStatus_4 extends _i1.SmartFake
    implements _i3.PasswordValidationStatus {
  _FakePasswordValidationStatus_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_5<T> extends _i1.SmartFake
    implements _i5.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResult_6<T> extends _i1.SmartFake
    implements _i6.PaginatedResult<T> {
  _FakePaginatedResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResult_7<T> extends _i1.SmartFake
    implements _i7.PaginatedResult<T> {
  _FakePaginatedResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i4.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_0(
          this,
          Invocation.getter(#app),
        ),
      ) as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
        Invocation.setter(
          #tenantId,
          tenantId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
        Invocation.setter(
          #customAuthDomain,
          customAuthDomain,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i8.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #useAuthEmulator,
          [
            host,
            port,
          ],
          {#automaticHostMapping: automaticHostMapping},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> applyActionCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #applyActionCode,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkActionCode,
          [code],
        ),
        returnValue: _i8.Future<_i3.ActionCodeInfo>.value(_FakeActionCodeInfo_1(
          this,
          Invocation.method(
            #checkActionCode,
            [code],
          ),
        )),
      ) as _i8.Future<_i3.ActionCodeInfo>);

  @override
  _i8.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [],
          {
            #code: code,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.UserCredential> getRedirectResult() => (super.noSuchMethod(
        Invocation.method(
          #getRedirectResult,
          [],
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #getRedirectResult,
            [],
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) => (super.noSuchMethod(
        Invocation.method(
          #isSignInWithEmailLink,
          [emailLink],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i4.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i8.Stream<_i4.User?>.empty(),
      ) as _i8.Stream<_i4.User?>);

  @override
  _i8.Stream<_i4.User?> idTokenChanges() => (super.noSuchMethod(
        Invocation.method(
          #idTokenChanges,
          [],
        ),
        returnValue: _i8.Stream<_i4.User?>.empty(),
      ) as _i8.Stream<_i4.User?>);

  @override
  _i8.Stream<_i4.User?> userChanges() => (super.noSuchMethod(
        Invocation.method(
          #userChanges,
          [],
        ),
        returnValue: _i8.Stream<_i4.User?>.empty(),
      ) as _i8.Stream<_i4.User?>);

  @override
  _i8.Future<void> sendPasswordResetEmail({
    required String? email,
    _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {
            #email: email,
            #actionCodeSettings: actionCodeSettings,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSignInLinkToEmail,
          [],
          {
            #email: email,
            #actionCodeSettings: actionCodeSettings,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setLanguageCode(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguageCode,
          [languageCode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSettings,
          [],
          {
            #appVerificationDisabledForTesting:
                appVerificationDisabledForTesting,
            #userAccessGroup: userAccessGroup,
            #phoneNumber: phoneNumber,
            #smsCode: smsCode,
            #forceRecaptchaFlow: forceRecaptchaFlow,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPersistence(_i3.Persistence? persistence) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPersistence,
          [persistence],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.UserCredential> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.UserCredential> signInWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithCredential,
          [credential],
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithCredential,
            [credential],
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithCustomToken,
          [token],
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithCustomToken,
            [token],
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailLink,
          [],
          {
            #email: email,
            #emailLink: emailLink,
          },
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithEmailLink,
            [],
            {
              #email: email,
              #emailLink: emailLink,
            },
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.UserCredential> signInWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithProvider,
          [provider],
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithProvider,
            [provider],
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<_i4.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i8.Future<_i4.ConfirmationResult>.value(_FakeConfirmationResult_3(
          this,
          Invocation.method(
            #signInWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i8.Future<_i4.ConfirmationResult>);

  @override
  _i8.Future<_i4.UserCredential> signInWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPopup,
          [provider],
        ),
        returnValue: _i8.Future<_i4.UserCredential>.value(_FakeUserCredential_2(
          this,
          Invocation.method(
            #signInWithPopup,
            [provider],
          ),
        )),
      ) as _i8.Future<_i4.UserCredential>);

  @override
  _i8.Future<void> signInWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithRedirect,
          [provider],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPasswordResetCode,
          [code],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #verifyPasswordResetCode,
            [code],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i3.PhoneMultiFactorInfo? multiFactorInfo,
    required _i3.PhoneVerificationCompleted? verificationCompleted,
    required _i3.PhoneVerificationFailed? verificationFailed,
    required _i3.PhoneCodeSent? codeSent,
    required _i3.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i3.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneNumber,
          [],
          {
            #phoneNumber: phoneNumber,
            #multiFactorInfo: multiFactorInfo,
            #verificationCompleted: verificationCompleted,
            #verificationFailed: verificationFailed,
            #codeSent: codeSent,
            #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
            #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
            #timeout: timeout,
            #forceResendingToken: forceResendingToken,
            #multiFactorSession: multiFactorSession,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> revokeTokenWithAuthorizationCode(
          String? authorizationCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeTokenWithAuthorizationCode,
          [authorizationCode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> initializeRecaptchaConfig() => (super.noSuchMethod(
        Invocation.method(
          #initializeRecaptchaConfig,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.PasswordValidationStatus> validatePassword(
    _i4.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validatePassword,
          [
            auth,
            password,
          ],
        ),
        returnValue: _i8.Future<_i3.PasswordValidationStatus>.value(
            _FakePasswordValidationStatus_4(
          this,
          Invocation.method(
            #validatePassword,
            [
              auth,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i3.PasswordValidationStatus>);
}

/// A class which mocks [FirebaseDatabaseServiceEnhanced].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseDatabaseServiceEnhanced extends _i1.Mock
    implements _i7.FirebaseDatabaseServiceEnhanced {
  MockFirebaseDatabaseServiceEnhanced() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  _i5.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i5.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> onInit() => (super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i6.PaginatedResult<_i10.TaskEntity>> getPaginatedTasks({
    required String? workspaceId,
    int? page = 1,
    int? pageSize = 20,
    String? lastTaskId,
    _i11.TaskStatus? status,
    _i11.TaskPriority? priority,
    _i11.TaskType? type,
    String? projectId,
    String? assigneeId,
    String? orderBy = r'createdAt',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginatedTasks,
          [],
          {
            #workspaceId: workspaceId,
            #page: page,
            #pageSize: pageSize,
            #lastTaskId: lastTaskId,
            #status: status,
            #priority: priority,
            #type: type,
            #projectId: projectId,
            #assigneeId: assigneeId,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue: _i8.Future<_i6.PaginatedResult<_i10.TaskEntity>>.value(
            _FakePaginatedResult_6<_i10.TaskEntity>(
          this,
          Invocation.method(
            #getPaginatedTasks,
            [],
            {
              #workspaceId: workspaceId,
              #page: page,
              #pageSize: pageSize,
              #lastTaskId: lastTaskId,
              #status: status,
              #priority: priority,
              #type: type,
              #projectId: projectId,
              #assigneeId: assigneeId,
              #orderBy: orderBy,
              #ascending: ascending,
            },
          ),
        )),
      ) as _i8.Future<_i6.PaginatedResult<_i10.TaskEntity>>);

  @override
  _i8.Future<_i6.PaginatedResult<_i12.Project>> getPaginatedProjects({
    required String? workspaceId,
    int? page = 1,
    int? pageSize = 20,
    String? lastProjectId,
    _i11.ProjectStatus? status,
    String? orderBy = r'createdAt',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginatedProjects,
          [],
          {
            #workspaceId: workspaceId,
            #page: page,
            #pageSize: pageSize,
            #lastProjectId: lastProjectId,
            #status: status,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue: _i8.Future<_i6.PaginatedResult<_i12.Project>>.value(
            _FakePaginatedResult_6<_i12.Project>(
          this,
          Invocation.method(
            #getPaginatedProjects,
            [],
            {
              #workspaceId: workspaceId,
              #page: page,
              #pageSize: pageSize,
              #lastProjectId: lastProjectId,
              #status: status,
              #orderBy: orderBy,
              #ascending: ascending,
            },
          ),
        )),
      ) as _i8.Future<_i6.PaginatedResult<_i12.Project>>);

  @override
  _i8.Future<_i7.PaginatedResult<_i13.ReportEntity>> getPaginatedReports({
    required String? workspaceId,
    int? page = 1,
    int? pageSize = 20,
    String? lastReportId,
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
    String? orderBy = r'createdAt',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginatedReports,
          [],
          {
            #workspaceId: workspaceId,
            #page: page,
            #pageSize: pageSize,
            #lastReportId: lastReportId,
            #userId: userId,
            #startDate: startDate,
            #endDate: endDate,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue: _i8.Future<_i7.PaginatedResult<_i13.ReportEntity>>.value(
            _FakePaginatedResult_7<_i13.ReportEntity>(
          this,
          Invocation.method(
            #getPaginatedReports,
            [],
            {
              #workspaceId: workspaceId,
              #page: page,
              #pageSize: pageSize,
              #lastReportId: lastReportId,
              #userId: userId,
              #startDate: startDate,
              #endDate: endDate,
              #orderBy: orderBy,
              #ascending: ascending,
            },
          ),
        )),
      ) as _i8.Future<_i7.PaginatedResult<_i13.ReportEntity>>);

  @override
  _i8.Future<List<_i10.TaskEntity>> getTasksOptimized({
    required String? workspaceId,
    _i11.TaskStatus? status,
    _i11.TaskPriority? priority,
    _i11.TaskType? type,
    String? projectId,
    String? assigneeId,
    int? limit,
    String? orderBy = r'createdAt',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksOptimized,
          [],
          {
            #workspaceId: workspaceId,
            #status: status,
            #priority: priority,
            #type: type,
            #projectId: projectId,
            #assigneeId: assigneeId,
            #limit: limit,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue:
            _i8.Future<List<_i10.TaskEntity>>.value(<_i10.TaskEntity>[]),
      ) as _i8.Future<List<_i10.TaskEntity>>);

  @override
  _i8.Future<List<_i12.Project>> getProjectsOptimized({
    required String? workspaceId,
    _i11.ProjectStatus? status,
    int? limit,
    String? orderBy = r'createdAt',
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectsOptimized,
          [],
          {
            #workspaceId: workspaceId,
            #status: status,
            #limit: limit,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue: _i8.Future<List<_i12.Project>>.value(<_i12.Project>[]),
      ) as _i8.Future<List<_i12.Project>>);

  @override
  _i8.Future<void> createUser(_i14.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i14.User?> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i8.Future<_i14.User?>.value(),
      ) as _i8.Future<_i14.User?>);

  @override
  _i8.Future<void> updateUser(_i14.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addUserToCompany({
    required String? userId,
    required String? workspaceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserToCompany,
          [],
          {
            #userId: userId,
            #workspaceId: workspaceId,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> createTask(_i10.TaskEntity? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i10.TaskEntity?> getTask(
    String? taskId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTask,
          [
            taskId,
            workspaceId,
          ],
        ),
        returnValue: _i8.Future<_i10.TaskEntity?>.value(),
      ) as _i8.Future<_i10.TaskEntity?>);

  @override
  _i8.Future<void> updateTask(_i10.TaskEntity? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteTask(
    String? taskId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [
            taskId,
            workspaceId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> createProject(_i12.Project? project) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [project],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createProject,
            [project],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i12.Project?> getProject(
    String? projectId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [
            projectId,
            workspaceId,
          ],
        ),
        returnValue: _i8.Future<_i12.Project?>.value(),
      ) as _i8.Future<_i12.Project?>);

  @override
  _i8.Future<void> updateProject(_i12.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [project],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteProject(
    String? projectId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [
            projectId,
            workspaceId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> createReport(_i13.ReportEntity? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReport,
          [report],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createReport,
            [report],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i13.ReportEntity?> getReport(
    String? reportId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReport,
          [
            reportId,
            workspaceId,
          ],
        ),
        returnValue: _i8.Future<_i13.ReportEntity?>.value(),
      ) as _i8.Future<_i13.ReportEntity?>);

  @override
  _i8.Future<void> updateReport(_i13.ReportEntity? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReport,
          [report],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteReport(
    String? reportId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReport,
          [
            reportId,
            workspaceId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> createInvitation(dynamic invitation) => (super.noSuchMethod(
        Invocation.method(
          #createInvitation,
          [invitation],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<dynamic> getInvitation(String? invitationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInvitation,
          [invitationId],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);

  @override
  _i8.Future<void> updateInvitationStatus({
    required String? invitationId,
    required String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInvitationStatus,
          [],
          {
            #invitationId: invitationId,
            #status: status,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> createUserWithPasswordChangeFlag({
    required String? userId,
    required String? email,
    required bool? mustChangePassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithPasswordChangeFlag,
          [],
          {
            #userId: userId,
            #email: email,
            #mustChangePassword: mustChangePassword,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i14.User?> getUserByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValue: _i8.Future<_i14.User?>.value(),
      ) as _i8.Future<_i14.User?>);

  @override
  _i8.Future<void> createNotification({
    required String? userId,
    required String? type,
    required String? title,
    required String? message,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotification,
          [],
          {
            #userId: userId,
            #type: type,
            #title: title,
            #message: message,
            #data: data,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeNotificationByType({
    required String? userId,
    required String? type,
    required String? invitationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeNotificationByType,
          [],
          {
            #userId: userId,
            #type: type,
            #invitationId: invitationId,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addWorkspaceMember(dynamic member) => (super.noSuchMethod(
        Invocation.method(
          #addWorkspaceMember,
          [member],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
