// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/integration/phase1_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todolist/core/errors/failures.dart' as _i5;
import 'package:todolist/features/workspace/domain/entities/workspace.dart'
    as _i6;
import 'package:todolist/features/workspace/domain/entities/workspace_member.dart'
    as _i7;
import 'package:todolist/features/workspace/domain/repositories/workspace_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepository extends _i1.Mock
    implements _i3.WorkspaceRepository {
  MockWorkspaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> createWorkspace(
          _i6.Workspace? workspace) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkspace,
          [workspace],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #createWorkspace,
            [workspace],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> getWorkspace(
          String? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspace,
          [workspaceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #getWorkspace,
            [workspaceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>> getUserWorkspaces(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserWorkspaces,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Workspace>>(
          this,
          Invocation.method(
            #getUserWorkspaces,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Workspace>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>> updateWorkspace(
          _i6.Workspace? workspace) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkspace,
          [workspace],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace>(
          this,
          Invocation.method(
            #updateWorkspace,
            [workspace],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteWorkspace(
          String? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkspace,
          [workspaceId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteWorkspace,
            [workspaceId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> switchToWorkspace(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchToWorkspace,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #switchToWorkspace,
            [
              userId,
              workspaceId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace?>> getCurrentWorkspace(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWorkspace,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Workspace?>(
          this,
          Invocation.method(
            #getCurrentWorkspace,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Workspace?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>> addMember(
          _i7.WorkspaceMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [member],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>.value(
                _FakeEither_0<_i5.Failure, _i7.WorkspaceMember>(
          this,
          Invocation.method(
            #addMember,
            [member],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeMember(
    String? workspaceId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            workspaceId,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeMember,
            [
              workspaceId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>
      updateMemberPermissions(
    String? workspaceId,
    String? userId,
    List<String>? permissions,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateMemberPermissions,
              [
                workspaceId,
                userId,
                permissions,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>.value(
                    _FakeEither_0<_i5.Failure, _i7.WorkspaceMember>(
              this,
              Invocation.method(
                #updateMemberPermissions,
                [
                  workspaceId,
                  userId,
                  permissions,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.WorkspaceMember>>>
      getWorkspaceMembers(String? workspaceId) => (super.noSuchMethod(
            Invocation.method(
              #getWorkspaceMembers,
              [workspaceId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i7.WorkspaceMember>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.WorkspaceMember>>(
              this,
              Invocation.method(
                #getWorkspaceMembers,
                [workspaceId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.WorkspaceMember>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember?>>
      getUserWorkspaceRole(
    String? userId,
    String? workspaceId,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUserWorkspaceRole,
              [
                userId,
                workspaceId,
              ],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember?>>.value(
                    _FakeEither_0<_i5.Failure, _i7.WorkspaceMember?>(
              this,
              Invocation.method(
                #getUserWorkspaceRole,
                [
                  userId,
                  workspaceId,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.WorkspaceMember?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> hasPermission(
    String? userId,
    String? workspaceId,
    String? permission,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [
            userId,
            workspaceId,
            permission,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #hasPermission,
            [
              userId,
              workspaceId,
              permission,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getUserPermissions(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPermissions,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getUserPermissions,
            [
              userId,
              workspaceId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}
