// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/integration/task_management_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i11;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:todolist/core/errors/failures.dart' as _i10;
import 'package:todolist/core/services/permission_service.dart' as _i8;
import 'package:todolist/core/services/workspace_context_service.dart' as _i3;
import 'package:todolist/features/auth/domain/entities/user.dart' as _i5;
import 'package:todolist/features/auth/presentation/controllers/auth_controller.dart'
    as _i9;
import 'package:todolist/features/tasks/domain/entities/project.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRx_1<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceContextService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceContextService extends _i1.Mock
    implements _i3.WorkspaceContextService {
  MockWorkspaceContextService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentWorkspaceId => (super.noSuchMethod(
        Invocation.getter(#currentWorkspaceId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#currentWorkspaceId),
        ),
      ) as String);

  @override
  List<_i5.User> get workspaceMembers => (super.noSuchMethod(
        Invocation.getter(#workspaceMembers),
        returnValue: <_i5.User>[],
      ) as List<_i5.User>);

  @override
  List<_i6.Project> get workspaceProjects => (super.noSuchMethod(
        Invocation.getter(#workspaceProjects),
        returnValue: <_i6.Project>[],
      ) as List<_i6.Project>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as String);

  @override
  bool get hasValidWorkspace => (super.noSuchMethod(
        Invocation.getter(#hasValidWorkspace),
        returnValue: false,
      ) as bool);

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> setCurrentWorkspace(String? workspaceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentWorkspace,
          [workspaceId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isWorkspaceMember(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isWorkspaceMember,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.User? getWorkspaceMember(String? userId) =>
      (super.noSuchMethod(Invocation.method(
        #getWorkspaceMember,
        [userId],
      )) as _i5.User?);

  @override
  bool isWorkspaceProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #isWorkspaceProject,
          [projectId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Project? getWorkspaceProject(String? projectId) =>
      (super.noSuchMethod(Invocation.method(
        #getWorkspaceProject,
        [projectId],
      )) as _i6.Project?);

  @override
  _i7.Future<void> refreshWorkspaceData() => (super.noSuchMethod(
        Invocation.method(
          #refreshWorkspaceData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clearWorkspaceContext() => super.noSuchMethod(
        Invocation.method(
          #clearWorkspaceContext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getWorkspaceContextInfo() => (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceContextInfo,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i8.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as String);

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<bool> hasPermission(
    String? userId,
    String? workspaceId,
    String? permission,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [
            userId,
            workspaceId,
            permission,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canCreateTask(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canCreateTask,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canAssignTask(
    String? userId,
    String? workspaceId,
    String? assigneeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAssignTask,
          [
            userId,
            workspaceId,
            assigneeId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canUpdateTaskStatus(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canUpdateTaskStatus,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canDeleteTask(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canDeleteTask,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canSetTaskPriority(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canSetTaskPriority,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canSetTaskDeadline(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canSetTaskDeadline,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canCreateProject(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canCreateProject,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canManageProject(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canManageProject,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canViewAllData(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canViewAllData,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canViewTeamData(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canViewTeamData,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canManageUsers(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canManageUsers,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> canInviteUsers(
    String? userId,
    String? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canInviteUsers,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void clearUserPermissions(
    String? userId,
    String? workspaceId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #clearUserPermissions,
          [
            userId,
            workspaceId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllPermissions() => super.noSuchMethod(
        Invocation.method(
          #clearAllPermissions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getPermissionDisplayText(String? permission) => (super.noSuchMethod(
        Invocation.method(
          #getPermissionDisplayText,
          [permission],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getPermissionDisplayText,
            [permission],
          ),
        ),
      ) as String);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i9.AuthController {
  MockAuthController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Rx<_i5.User?> get currentUserObservable => (super.noSuchMethod(
        Invocation.getter(#currentUserObservable),
        returnValue: _FakeRx_1<_i5.User?>(
          this,
          Invocation.getter(#currentUserObservable),
        ),
      ) as _i2.Rx<_i5.User?>);

  @override
  bool get hasCompany => (super.noSuchMethod(
        Invocation.getter(#hasCompany),
        returnValue: false,
      ) as bool);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
      ) as bool);

  @override
  bool get isDepartmentManager => (super.noSuchMethod(
        Invocation.getter(#isDepartmentManager),
        returnValue: false,
      ) as bool);

  @override
  bool get isTeamLead => (super.noSuchMethod(
        Invocation.getter(#isTeamLead),
        returnValue: false,
      ) as bool);

  @override
  bool get isRegularUser => (super.noSuchMethod(
        Invocation.getter(#isRegularUser),
        returnValue: false,
      ) as bool);

  @override
  bool get isCompanyAdmin => (super.noSuchMethod(
        Invocation.getter(#isCompanyAdmin),
        returnValue: false,
      ) as bool);

  @override
  bool get isDepartmentAdmin => (super.noSuchMethod(
        Invocation.getter(#isDepartmentAdmin),
        returnValue: false,
      ) as bool);

  @override
  String get userDisplayName => (super.noSuchMethod(
        Invocation.getter(#userDisplayName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#userDisplayName),
        ),
      ) as String);

  @override
  String get userInitials => (super.noSuchMethod(
        Invocation.getter(#userInitials),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#userInitials),
        ),
      ) as String);

  @override
  String get companyDisplayName => (super.noSuchMethod(
        Invocation.getter(#companyDisplayName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#companyDisplayName),
        ),
      ) as String);

  @override
  String get companyInitials => (super.noSuchMethod(
        Invocation.getter(#companyInitials),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#companyInitials),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isSuccess => (super.noSuchMethod(
        Invocation.getter(#isSuccess),
        returnValue: false,
      ) as bool);

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isSuccess(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isSuccess,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void setAuthenticatedUserForTest(
    String? id,
    String? email,
    String? name,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAuthenticatedUserForTest,
          [
            id,
            email,
            name,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> handlePostLoginNavigation() => (super.noSuchMethod(
        Invocation.method(
          #handlePostLoginNavigation,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> changePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [newPassword],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserProfile({
    String? name,
    String? profileImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #name: name,
            #profileImageUrl: profileImageUrl,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> createCompany({
    required String? name,
    String? description,
    String? departmentName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCompany,
          [],
          {
            #name: name,
            #description: description,
            #departmentName: departmentName,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool hasPermission(String? permission) => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [permission],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canManageRole(String? targetRole) => (super.noSuchMethod(
        Invocation.method(
          #canManageRole,
          [targetRole],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasHigherAuthorityThan(String? targetRole) => (super.noSuchMethod(
        Invocation.method(
          #hasHigherAuthorityThan,
          [targetRole],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String> getCurrentUserPermissions() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserPermissions,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void setError(_i10.Failure? failure) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [failure],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearStates() => super.noSuchMethod(
        Invocation.method(
          #clearStates,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleError(_i10.Failure? failure) => super.noSuchMethod(
        Invocation.method(
          #handleError,
          [failure],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleSuccess([String? message]) => super.noSuchMethod(
        Invocation.method(
          #handleSuccess,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<T?> executeAsync<T>(
    _i7.Future<T> Function()? operation, {
    bool? showLoading = true,
    String? successMessage,
    bool? showError = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeAsync,
          [operation],
          {
            #showLoading: showLoading,
            #successMessage: successMessage,
            #showError: showError,
          },
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<T?> navigateTo<T>(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<T?> navigateOffAll<T>(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateOffAll,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<T?> navigateOff<T>(
    String? routeName, {
    dynamic arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateOff,
          [routeName],
          {#arguments: arguments},
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  void navigateBack<T>({T? result}) => super.noSuchMethod(
        Invocation.method(
          #navigateBack,
          [],
          {#result: result},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateBackToRoot() => super.noSuchMethod(
        Invocation.method(
          #navigateBackToRoot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<T?> showDialog<T>(
    _i11.Widget? child, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [child],
          {#name: name},
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<T?> showBottomSheet<T>(
    _i11.Widget? child, {
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [child],
          {#name: name},
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  _i7.Future<T?> showAlertDialog<T>({
    required String? title,
    required String? message,
    String? confirmText,
    String? cancelText,
    _i12.VoidCallback? onConfirm,
    _i12.VoidCallback? onCancel,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlertDialog,
          [],
          {
            #title: title,
            #message: message,
            #confirmText: confirmText,
            #cancelText: cancelText,
            #onConfirm: onConfirm,
            #onCancel: onCancel,
            #name: name,
          },
        ),
        returnValue: _i7.Future<T?>.value(),
      ) as _i7.Future<T?>);

  @override
  void printNavigationState() => super.noSuchMethod(
        Invocation.method(
          #printNavigationState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Disposer addListener(_i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i13.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i12.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Disposer addListenerId(
    Object? key,
    _i13.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i13.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
